name: CI
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
            mkdir -p /apps/sync_audio/
            cd /apps/sync_audio/
            git pull
            source /apps/sync_audio/.venv/bin/activate
            pip install -r requirements.txt
            cp /apps/sync_audio/config/sync_audio_daphne.service /etc/systemd/system/
            cp /apps/sync_audio/config/sync_audio_gunicorn.service /etc/systemd/system/
            cp /apps/sync_audio/config/sync_audio_nginx.conf /etc/nginx/nginx.conf
            python manage.py migrate
            python manage.py collectstatic --noinput
            systemctl daemon-reload
            systemctl restart sync_audio_gunicorn
            systemctl restart sync_audio_daphne
            systemctl restart redis-server
            systemctl restart nginx
